In [8]:
import pandas as pd

In [9]:
##geracion_anual()
# generacion_anual


##detalles_panel()
#potencia_calculada

#DATA
#caracteristicas_panel
def generacion_anual_anos(generacion_anual:float , potencia_calculada:float, caracteristicas_panel:int):
    generacion_anual_anos_data= []

    if caracteristicas_panel == 540:
        degradacion_anual=0.0045

    for a in range(26):

        if a == 0:
            factor_degradacion=0
            generacion_anual_anos_info=0
            kwh=0

        elif a == 1:
            factor_degradacion=1
            generacion_anual_anos_info = generacion_anual
            kwh = generacion_anual_anos_info/potencia_calculada

        else:
            factor_degradacion = factor_degradacion-degradacion_anual
            generacion_anual_anos_info=generacion_anual * factor_degradacion

            kwh = generacion_anual_anos_info/potencia_calculada

        generacion_anual_anos_data.append({
            "Año" : a,
            "Factor degradacion": factor_degradacion,
            "Generacion año": generacion_anual_anos_info,
            "kWh/kWp": kwh,
        })

    return generacion_anual_anos_data

In [10]:
generacion_anual_anos_met = generacion_anual_anos(457695.970875, 259.74, 540)
data_generacion_anual_anos = pd.DataFrame(generacion_anual_anos_met)
data_generacion_anual_anos

    Año  Factor degradacion  Generacion año      kWh/kWp
0     0              0.0000        0.000000     0.000000
1     1              1.0000   457695.970875  1762.131250
2     2              0.9955   455636.339006  1754.201659
3     3              0.9910   453576.707137  1746.272069
4     4              0.9865   451517.075268  1738.342478
5     5              0.9820   449457.443399  1730.412888
6     6              0.9775   447397.811530  1722.483297
7     7              0.9730   445338.179661  1714.553706
8     8              0.9685   443278.547792  1706.624116
9     9              0.9640   441218.915924  1698.694525
10   10              0.9595   439159.284055  1690.764934
11   11              0.9550   437099.652186  1682.835344
12   12              0.9505   435040.020317  1674.905753
13   13              0.9460   432980.388448  1666.976163
14   14              0.9415   430920.756579  1659.046572
15   15              0.9370   428861.124710  1651.116981
16   16              0.9325   426801.492841  1643.187391
17   17              0.9280   424741.860972  1635.257800
18   18              0.9235   422682.229103  1627.328209
19   19              0.9190   420622.597234  1619.398619
20   20              0.9145   418562.965365  1611.469028
21   21              0.9100   416503.333496  1603.539438
22   22              0.9055   414443.701627  1595.609847
23   23              0.9010   412384.069758  1587.680256
24   24              0.8965   410324.437889  1579.750666
25   25              0.8920   408264.806021  1571.821075